### ISSUE TITLE
도메인 설계

### ISSUE THREAD

**Issue by Domae-back-end** [cocktail-board/3-team-study#28]
https://docs.google.com/spreadsheets/d/1FgRuH_KHdQHXH4Fvtq0HJwViND8WMnw7n3r6_6z1Z-Y/edit?usp=sharing

구글 스프레드 시트를 통해 도메인 설계

**Comment by munyeol-Yoon** [comment]
초기 도메인 설계 완료
기능이 추가되면 다시 수정
